// Fallback for using MaterialIcons on Android and web.

import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { SymbolWeight, SymbolViewProps } from "expo-symbols";
import { ComponentProps } from "react";
import { OpaqueColorValue, type StyleProp, type TextStyle } from "react-native";

type IconMapping = Record<SymbolViewProps["name"], ComponentProps<typeof MaterialIcons>["name"]>;
type IconSymbolName = keyof typeof MAPPING;

/**
 * SF Symbols → Material Icons mapping
 */
const MAPPING = {
  // Navigation
  "house.fill": "home",
  "paperplane.fill": "send",
  "chevron.left.forwardslash.chevron.right": "code",
  "chevron.right": "chevron-right",
  "chevron.left": "chevron-left",
  "chevron.down": "expand-more",
  "chevron.up": "expand-less",
  // Tabs
  "chart.bar.fill": "bar-chart",
  "tray.full.fill": "inbox",
  "archivebox.fill": "inventory-2",
  "gearshape.fill": "settings",
  "building.2.fill": "business",
  // Actions
  "plus": "add",
  "plus.circle.fill": "add-circle",
  "xmark": "close",
  "xmark.circle.fill": "cancel",
  "checkmark": "check",
  "checkmark.circle.fill": "check-circle",
  "arrow.up.circle.fill": "upload",
  "arrow.down.circle.fill": "download",
  "square.and.arrow.up": "share",
  "doc.fill": "description",
  "doc.text.fill": "article",
  "photo.fill": "image",
  "paperclip": "attach-file",
  "trash.fill": "delete",
  "pencil": "edit",
  "magnifyingglass": "search",
  "bell.fill": "notifications",
  "bell.badge.fill": "notifications-active",
  "star.fill": "star",
  "star": "star-border",
  "heart.fill": "favorite",
  "bookmark.fill": "bookmark",
  "tag.fill": "label",
  "person.fill": "person",
  "person.2.fill": "people",
  "globe": "language",
  "link": "link",
  "phone.fill": "phone",
  "envelope.fill": "email",
  "message.fill": "chat",
  "bubble.left.fill": "chat-bubble",
  "mic.fill": "mic",
  "mic.slash.fill": "mic-off",
  "speaker.wave.2.fill": "volume-up",
  "waveform": "graphic-eq",
  "bolt.fill": "bolt",
  "sparkles": "auto-awesome",
  "brain.head.profile": "psychology",
  "cpu.fill": "memory",
  "network": "hub",
  "wifi": "wifi",
  "lock.fill": "lock",
  "key.fill": "key",
  "eye.fill": "visibility",
  "eye.slash.fill": "visibility-off",
  "info.circle.fill": "info",
  "exclamationmark.triangle.fill": "warning",
  "clock.fill": "access-time",
  "calendar": "calendar-today",
  "arrow.clockwise": "refresh",
  "arrow.counterclockwise": "undo",
  "arrow.right": "arrow-forward",
  "arrow.left": "arrow-back",
  "arrow.up": "arrow-upward",
  "arrow.down": "arrow-downward",
  "arrow.up.right": "open-in-new",
  "square.grid.2x2.fill": "grid-view",
  "list.bullet": "list",
  "slider.horizontal.3": "tune",
  "line.3.horizontal.decrease": "filter-list",
  "square.and.pencil": "edit-note",
  "chart.line.uptrend.xyaxis": "trending-up",
  "chart.line.downtrend.xyaxis": "trending-down",
  "dollarsign.circle.fill": "monetization-on",
  "shippingbox.fill": "inventory",
  "bag.fill": "shopping-bag",
  "cart.fill": "shopping-cart",
  "trophy.fill": "emoji-events",
  "flag.fill": "flag",
  "mappin.fill": "place",
  "location.fill": "my-location",
  "map.fill": "map",
  "qrcode": "qr-code",
  "barcode": "barcode-reader",
  "camera.fill": "camera-alt",
  "video.fill": "videocam",
  "play.fill": "play-arrow",
  "pause.fill": "pause",
  "stop.fill": "stop",
  "forward.fill": "fast-forward",
  "backward.fill": "fast-rewind",
  "repeat": "repeat",
  "shuffle": "shuffle",
  "moon.fill": "dark-mode",
  "sun.max.fill": "light-mode",
  "circle.fill": "circle",
  "square.fill": "square",
  "rectangle.fill": "rectangle",
  "triangle.fill": "change-history",
  "seal.fill": "verified",
  "rosette": "workspace-premium",
  "crown.fill": "workspace-premium",
  "flame.fill": "local-fire-department",
  "leaf.fill": "eco",
  "hand.thumbsup.fill": "thumb-up",
  "hand.thumbsdown.fill": "thumb-down",
  "face.smiling.fill": "sentiment-satisfied",
  "antenna.radiowaves.left.and.right": "cell-tower",
  "iphone": "smartphone",
  "laptopcomputer": "laptop",
  "desktopcomputer": "desktop-mac",
  "externaldrive.fill": "storage",
  "folder.fill": "folder",
  "tray.fill": "inbox",
  "envelope.open.fill": "drafts",
  "arrow.up.doc.fill": "upload-file",
  "arrow.down.doc.fill": "download",
  "doc.badge.plus": "note-add",
  "doc.on.doc.fill": "file-copy",
  "text.alignleft": "format-align-left",
  "text.aligncenter": "format-align-center",
  "text.alignright": "format-align-right",
  "bold": "format-bold",
  "italic": "format-italic",
  "underline": "format-underlined",
  "paintbrush.fill": "brush",
  "paintpalette.fill": "palette",
  "wand.and.stars": "auto-fix-high",
  "scissors": "content-cut",
  "doc.on.clipboard.fill": "content-paste",
  "arrow.up.and.down": "swap-vert",
  "arrow.left.and.right": "swap-horiz",
  "arrow.up.left.and.arrow.down.right": "fullscreen",
  "arrow.down.right.and.arrow.up.left": "fullscreen-exit",
  "sidebar.left": "view-sidebar",
  "rectangle.split.3x1.fill": "view-column",
  "square.3.layers.3d.down.right": "layers",
  "plus.square.fill.on.square.fill": "add-to-photos",
  "minus.circle.fill": "remove-circle",
  "ellipsis": "more-horiz",
  "ellipsis.circle.fill": "more-vert",
  "square.on.square.fill": "copy-all",
  "externaldrive.badge.plus": "add-to-drive",
  "arrow.triangle.2.circlepath": "sync",
  "icloud.fill": "cloud",
  "icloud.and.arrow.up.fill": "cloud-upload",
  "icloud.and.arrow.down.fill": "cloud-download",
} as unknown as IconMapping;

/**
 * An icon component that uses native SF Symbols on iOS, and Material Icons on Android and web.
 */
export function IconSymbol({
  name,
  size = 24,
  color,
  style,
}: {
  name: IconSymbolName;
  size?: number;
  color: string | OpaqueColorValue;
  style?: StyleProp<TextStyle>;
  weight?: SymbolWeight;
}) {
  return <MaterialIcons color={color} size={size} name={MAPPING[name]} style={style} />;
}
